### ISSUE TITLE
Got a random freeze at installing Big Sur

### ISSUE THREAD

**Issue by nhanpiti** [RmondJone/i5-10600_H410TM-ITX_Hackintosh#2]
First of all, thanks for sharing EFI on H410TM-ITX hardware, it's so amazing. I follow your EFI (10400 instead). But, my system got a random freeze at installing, even after successfully installed, it still got freeze sometime. My PC works normally on Windows 10, so I believe hardware is still good. Could you give me some advice or a BIOS setting. One again, thank you so much.

**Comment by RmondJone** [comment]
建议-v开启日志查看报错，然后根据报错日志查看原因，对应的google搜索错误。我猜测你的冻屏问题大概率是UHD630显卡驱动不对的原因，你可以使用hackintool工具重新定制显卡驱动看看，不要直接用我的efi文件里的核显配置。
